swagger: '2.0'
# This is your document metadata
info:
  version: "0.0.1"
  title: TODO API
  description: an API for managing todo lists and getting have-done lists
  contact:
    name: MerlinBecker
    url: https://github.com/merlinbecker/Todo_API
host: merl.be
basePath: /todo
# Describe your paths here
schemes: ["http"]

security:
  - UserSecurity: []
  
paths:
  /{username}:
    get:
      description: get a list of all projects the user has
      parameters:
      - name: username 
        in: path
        type: string
        required: true
        description: The name of the user
      responses: 
        200: 
          description: successful returned list of projects
          schema:
            type: array
            items:
              $ref: "#/definitions/projectObj"
          examples:
            application/json: |-
              [{
                 "projectname":"foo",
                 "todos": 10,
                 "havedones":5,
                 "rel":"http://example.com/foouser/foo"
              },{...}]
        401:
          description: No access, because wrong login data
      security:
        - UserSecurity: []
    post:
      description: post todo object(s) into the list
      parameters:
      - name: username 
        in: path
        type: string
        required: true
        description: The name of the user
      - name: todos
        required: true
        in: body
        description: array of new tasks
        schema:
          type: array
          items:
            $ref: "#/definitions/taskObj"
      security:
        - UserSecurity: []
      responses:
        201: 
          description: Tasks have been created
        401:
          description: No permission to create todos
        400: 
          description: insufficient or wrong data
  /tasks/{id}:
    get:
      description: get a specific task by id
      parameters:
      - name: id 
        in: path
        type: integer
        required: true
        description: The task by it's id
      security: 
         - UserSecurity: []
      responses:
        200:
          description: successful returned todo list
        401:
          description: No access, because wrong user login data
    put:
      parameters:
      - name: id 
        in: path
        type: integer
        required: true
        description: the tasks ID
      security: 
         - UserSecurity: []
      responses:
        200:
          description: successful modified
        401:
          description: No access, because wrong user login data
        400: 
          description: insufficient or wrong data
  /{username}/{projectname}:
    get:
      description: get all tasks for user {username} and project {projectname}. set project to "all" for all todos of every project
      parameters:
        - name: username 
          in: path
          type: string
          required: true
          description: The name of the user
        - name: projectname 
          in: path
          type: string
          required: true
          description: The name of the project
      security:
        - UserSecurity: []
      responses:
        200:
          description: successful returned task list
          schema:
            type: array
            items:
              $ref: "#/definitions/brief_taskobj"
          examples:
            application/json: |-
              [{
                 "description":"footask",
                 "status":"todo",
                 "rel":"http://example.com/tasks/5"
              },{...}]
        401:
          description: No access, because wrong user login data
  
  /users:
    get:
      description: Gets all todo list users
      responses:
        200:
          description: successful users response
          schema:
            type: array
            items:
              $ref: "#/definitions/userObj"
          examples:
            application/json: |-
              [{
                 "u_id":1,
                 "u_name":"foo",
                 "u_email":"foo@example.com"
              },{...}]
        401:
          description: No access, because wrong login data
      produces:
        - application/json
      security: 
        - AdminSecurity: []
    delete:
      description: deletes a user from the list
      consumes:
        - application/json
      parameters:
        - name: user
          required: true
          in: body
          description: data for new user
          schema:
            type: array
            items: 
              $ref: "#/definitions/userObj"
      security:
        - AdminSecurity: []
      responses:
        200: 
          description: user deleted
        400: 
          description: insufficient or wrong data
    post: 
      description: adds user to the list
      consumes:
        - application/json
      parameters:
        - name: user
          required: true
          in: body
          description: data for new user
          schema:
            $ref: "#/definitions/newUserObj"
      security:
        - AdminSecurity: []
      responses:
        201: 
          description: a new user was created
        400: 
          description: insufficient or wrong data
          
  # This is a path endpoint. Change it.
  /settings:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: Gets the settings with which the server is running
      produces:
      - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: successful settings response
          schema:
            $ref: "#/definitions/settingsObj"
          examples:
            application/json: |-
              {
                "uses_basic_auth": true,
                "basic_auth_admin": "todoadmin",
                "basic_auth_pw": "root",
                "db_host": "localhost",
                "db_user": "root",
                "db_password": "root",
                "db_database":"todo_db"
              }
        501: 
          description: Server not set up, misses specified data
          schema: 
            $ref: "#/definitions/settingsObj"
          examples:
            application/json: |-
              [
              "uses_basic_auth",
              "db_host",
              "db_user",
              "db_password",
              "db_database"
              ]
        401:
          description: No access, because wrong login data
      security:
        - AdminSecurity: []
    put:
      description: alters settings for the server
      consumes:
        - application/json
      parameters:
        - name: settings
          required: true
          in: body
          description: The settings JSON transmitted to the server
          schema:
            $ref: "#/definitions/settingsObj"
      security:
        - AdminSecurity: []
      responses:
        201:
          description: Settings successfully created
        401:
          description: No Access, because login data are missing (if already defined in settings)
securityDefinitions:
  UserSecurity:
    type: basic
  AdminSecurity:
    type: basic
    
definitions:
  projectObj:
    type: object
    properties:
      projectname: 
        type: string
      todos:
        type: integer
      havedones:
        type: integer
      rel:
        type: string
  brief_taskobj:
    type: object
    properties:
      description:
        type: string
      status:
        type: string
      rel:
        type: string
  taskObj:
    type: object
    required: [task_description]
    properties:
      task_id:
        type: integer
        description: not considered when inserting a task
      task_description:
        type: string
      urgent:
        type: boolean
      important:
        type: boolean
      status:
        type: string
        enum: ["todo", "have-done", "cancelled"]
        description: default is 'todo'
      deadline: 
        type: string
        format: date
      repeat_interval:
        type: string
      repeat_since:
        type: string
      repeat_until:
        type: string
      projects:
        type: array
        items:
          type: string
  newUserObj:
    type: object
    properties:
      username: 
        type: string
      user_email:
        type: string
      user_password:
        type: string
        format: password
      user_pw_repeat:
        type: string
        format: password
  
  userObj:
    type: object
    properties:
      u_id:
        type: integer
      u_name:
        type: string
      u_email:
        type: string
        
  settingsObj:
    type: object
    properties:
      uses_basic_auth:
        type: boolean
      basic_auth_admin:
        type: string
      basic_auth_pw:
        type: string
        format: password
      db_host:
        type: string
      db_user:
        type: string
      db_password:
        type: string
        format: password
      db_database:
        type: string